// Catálogo de produtos da Cronos Exclusivo
// Para migrar para CMS: substituir este array por chamadas à API do Sanity ou Strapi.

export interface ProductSpec {
  caixa: string
  movimento: string
  calibre: string
  reservaDeMarcha?: string
  resistenciaAgua: string
  pulseira: string
  diametro?: string
  espessura?: string
  cristal?: string
  funcoes?: string
}

export interface Product {
  id: string
  slug: string
  brand: string
  model: string
  reference: string
  year?: number
  condition: 'Como novo' | 'Excelente' | 'Bom' | 'Novo (lacrado)'
  fullSet: boolean
  price: number | null // null = "Sob consulta"
  images: string[]    // caminhos em /public/products/
  description: string
  specs: ProductSpec
  featured: boolean
  hidden?: boolean // true = produto oculto do site (ex: aguardando fotos sem preço na imagem)
  prontaEntrega?: boolean // true = peça em estoque físico em Fortaleza, disponível para retirada/entrega imediata
}

export const products: Product[] = [
  // ─── SEIKO ──────────────────────────────────────────────────────────────────

  {
    id: '1',
    slug: 'seiko-5-sports-srpk33k1',
    brand: 'Seiko',
    model: '5 Sports Diver',
    reference: 'SRPK33K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-srpk33k1.jpg'],
    description:
      'Diver automático com mostrador verde e bezel preto. O 5 Sports une DNA esportivo e movimento automático em um pacote acessível sem abrir mão de personalidade. Full set com caixa Seiko original.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
    },
    featured: true,
  },
  {
    id: '2',
    slug: 'seiko-5-sports-srpe57k1',
    brand: 'Seiko',
    model: '5 Sports Automatic',
    reference: 'SRPE57K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-srpe57k1.jpg'],
    description:
      'Mostrador cinza carvão com ponteiros dourados e bracelê jubilê em aço. Silhueta clássica do 5 Sports com acabamento refinado para uso diário.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '40mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável (jubilê)',
    },
    featured: false,
  },
  {
    id: '3',
    slug: 'seiko-chronograph-ssb385p1',
    brand: 'Seiko',
    model: 'Chronograph Quartz',
    reference: 'SSB385P1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-ssb385p1.jpg'],
    description:
      'Cronógrafo a quartzo com mostrador verde e taquímetro. Combinação de pulseira em couro marrom e caixa em aço posiciona este Seiko entre os mais versáteis do catálogo — esporte e formalidade no mesmo pulso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '44mm',
      cristal: 'Hardlex',
      movimento: 'Quartzo (cronógrafo)',
      calibre: 'Seiko Cal. 8T63',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Couro marrom',
      funcoes: 'Cronógrafo, taquímetro, data',
    },
    featured: false,
  },
  {
    id: '4',
    slug: 'seiko-chronograph-ssb477p1',
    brand: 'Seiko',
    model: 'Chronograph Panda',
    reference: 'SSB477P1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-ssb477p1.jpg'],
    description:
      'Mostrador panda — fundo azul com subdials brancos — sobre bracelê de aço. Uma das composições cromáticas mais procuradas em cronógrafos acessíveis. Taquímetro e acabamento polido.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '43mm',
      cristal: 'Hardlex',
      movimento: 'Quartzo (cronógrafo)',
      calibre: 'Seiko Cal. 8T63',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Cronógrafo, taquímetro, data',
    },
    featured: true,
  },
  {
    id: '5',
    slug: 'seiko-prospex-ssc939p1',
    brand: 'Seiko',
    model: 'Prospex Solar Chronograph',
    reference: 'SSC939P1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-ssc939p1.jpg'],
    description:
      'Cronógrafo solar da linha Prospex com bezel azul e mostrador cinza grafite. Tecnologia solar Seiko elimina trocas de bateria mantendo a precisão de quartzo. Ideal para uso intenso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '44mm',
      cristal: 'Hardlex',
      movimento: 'Solar (quartzo)',
      calibre: 'Seiko Cal. V192',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Cronógrafo solar, data',
    },
    featured: true,
  },
  {
    id: '6',
    slug: 'seiko-5-sports-srpd57k1',
    brand: 'Seiko',
    model: '5 Sports Field',
    reference: 'SRPD57K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-srpd57k1.jpg'],
    description:
      'Versão field do 5 Sports com bezel funcional e mostrador cinza-esverdeado com detalhes em amarelo. Combinação incomum que resulta em alto reconhecimento visual no pulso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
    },
    featured: false,
  },
  {
    id: '7',
    slug: 'seiko-5-sports-srph33k1',
    brand: 'Seiko',
    model: '5 Sports Field Nylon',
    reference: 'SRPH33K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-srph33k1.jpg'],
    description:
      'Field watch automático com caixa em PVD preto e mostrador preto/laranja. Pulseira NATO em nylon reforçado entrega robustez e estilo aventureiro. Um dos formatos mais usados atualmente.',
    specs: {
      caixa: 'Aço inoxidável PVD preto',
      diametro: '39,4mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Nylon preto (NATO)',
    },
    featured: false,
  },
  {
    id: '8',
    slug: 'seiko-dress-srk059l',
    brand: 'Seiko',
    model: 'Dress Sapphire',
    reference: 'SRK059L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-srk059l.jpg'],
    description:
      'Dress watch de quartzo com mostrador branco e algarismos romanos sobre caixa dourada. Cristal de safira garante resistência a arranhões. Pequeno segundos a 6h confere acabamento clássico sem excessos.',
    specs: {
      caixa: 'Aço inoxidável banhado a ouro',
      diametro: '30,5mm',
      cristal: 'Safira',
      movimento: 'Quartzo',
      calibre: 'Seiko Cal. 4N40',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Couro marrom crocodilo',
      funcoes: 'Hora, pequeno segundos',
    },
    featured: false,
  },

  // ─── CITIZEN ─────────────────────────────────────────────────────────────────

  {
    id: '9',
    slug: 'citizen-zenshin-ca4610-85m',
    brand: 'Citizen',
    model: 'Zenshin Eco-Drive Chrono',
    reference: 'CA4610-85M',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ca4610-85m.jpg'],
    description:
      'Cronógrafo Eco-Drive em titânio super-leve com mostrador azul-gelado texturizado. O Zenshin é o topo do que a Citizen oferece em cronógrafos esportivos — tecnologia solar, titânio e design de alto impacto.',
    specs: {
      caixa: 'Titânio',
      diametro: '44mm',
      cristal: 'Safira',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. 8620',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Titânio',
      funcoes: 'Cronógrafo, data, Eco-Drive',
    },
    featured: true,
  },
  {
    id: '10',
    slug: 'citizen-tsuyosa-nj0150-56w',
    brand: 'Citizen',
    model: 'Tsuyosa Automatic',
    reference: 'NJ0150-56W',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-nj0150-56w.jpg'],
    description:
      'Automático com mostrador vermelho vivo em caixa de aço polido. O Tsuyosa é a linha que levou o automático da Citizen ao mainstream — silhueta contemporânea inspirada nos grandes dress watches japoneses.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8210',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
    },
    featured: false,
  },
  {
    id: '11',
    slug: 'citizen-tsuyosa-nj0150-56x',
    brand: 'Citizen',
    model: 'Tsuyosa Automatic Verde',
    reference: 'NJ0150-56X',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-nj0150-56x.jpg'],
    description:
      'Variação do Tsuyosa em aço com mostrador verde. Uma das cores mais procuradas da linha, com bracelê integrado e acabamento polido/escovado que valoriza o pulso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8210',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
    },
    featured: false,
  },
  {
    id: '12',
    slug: 'citizen-tsuyosa-nj0152-51x',
    brand: 'Citizen',
    model: 'Tsuyosa Automatic Gold',
    reference: 'NJ0152-51X',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-nj0152-51x.jpg'],
    description:
      'Tsuyosa em versão dourada com mostrador verde — combinação de alto impacto visual. Caixa e bracelê banhados oferecem o visual premium do gold sem o peso de um relógio sólido.',
    specs: {
      caixa: 'Aço inoxidável banhado a ouro',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8210',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço banhado a ouro',
    },
    featured: true,
  },
  {
    id: '13',
    slug: 'citizen-ecodrive-ca7048-08l',
    brand: 'Citizen',
    model: 'Eco-Drive Chrono Field',
    reference: 'CA7048-08L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ca7048-08l.jpg'],
    description:
      'Cronógrafo Eco-Drive com caixa escura e mostrador azul sobre pulseira de couro azul. Estética field watch com tecnologia solar — sem bateria, sem preocupação.',
    specs: {
      caixa: 'Aço inoxidável PVD preto',
      diametro: '44mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. B642',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Couro azul',
      funcoes: 'Cronógrafo, data, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '14',
    slug: 'citizen-tsuyosa-40mm-nk5010-51l',
    brand: 'Citizen',
    model: 'Tsuyosa 40mm Azul',
    reference: 'NK5010-51L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-nk5010-51l.jpg'],
    description:
      'Tsuyosa de 40mm com mostrador azul texturizado e pequeno segundos a 6h. Tamanho mais compacto e presença discreta no pulso — ideal para quem prefere relógios menores com personalidade.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8322',
      reservaDeMarcha: '42 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Hora, pequeno segundos',
    },
    featured: false,
  },
  {
    id: '15',
    slug: 'citizen-tsuyosa-40mm-nk5010-51x',
    brand: 'Citizen',
    model: 'Tsuyosa 40mm Champagne',
    reference: 'NK5010-51X',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-nk5010-51x.jpg'],
    description:
      'Tsuyosa 40mm two-tone com mostrador champagne e bracelê bicolor. Dress watch automático com acabamento impecável — um dos relógios mais elegantes do catálogo.',
    specs: {
      caixa: 'Aço inoxidável two-tone',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8322',
      reservaDeMarcha: '42 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço two-tone (prata/dourado)',
      funcoes: 'Hora, pequeno segundos',
    },
    featured: false,
  },
  {
    id: '16',
    slug: 'citizen-zenshin-aw0130-85l',
    brand: 'Citizen',
    model: 'Zenshin Eco-Drive Titânio Azul',
    reference: 'AW0130-85L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-aw0130-85l.jpg'],
    description:
      'Zenshin em titânio ultra-leve com mostrador azul jeans texturizado. Day-date completo e tecnologia Eco-Drive. Caixa com formato arrojado e escovado fino — leveza real no pulso.',
    specs: {
      caixa: 'Titânio',
      diametro: '43mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. J800',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Titânio',
      funcoes: 'Hora, data, dia da semana, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '17',
    slug: 'citizen-zenshin-aw0130-85x',
    brand: 'Citizen',
    model: 'Zenshin Eco-Drive Titânio Teal',
    reference: 'AW0130-85X',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-aw0130-85x.jpg'],
    description:
      'Versão teal-verde do Zenshin em titânio. Mostrador com textura única que muda de tom conforme a incidência de luz. Um dos relógios de maior apelo visual do estoque atual.',
    specs: {
      caixa: 'Titânio',
      diametro: '43mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. J800',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Titânio',
      funcoes: 'Hora, data, dia da semana, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '18',
    slug: 'citizen-promaster-ny0160-66e',
    brand: 'Citizen',
    model: 'Promaster Diver Automático',
    reference: 'NY0160-66E',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ny0160-66e.jpg'],
    description:
      'Diver automático da linha Promaster com mostrador preto e bezel preto/dourado. Certificação ISO 6425 para mergulho profissional. Day-date e movimento automático Cal. 8204 sem bateria.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '46mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8204',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '200m / 20 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Data, dia da semana, bezel unidirecional',
    },
    featured: false,
  },
  {
    id: '19',
    slug: 'citizen-ecodrive-aw1740-54l',
    brand: 'Citizen',
    model: 'Eco-Drive Elegance',
    reference: 'AW1740-54L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-aw1740-54l.jpg'],
    description:
      'Eco-Drive com mostrador azul texturizado e bracelê jubilê de cinco elos. Bezel com acabamento facetado e coroa de cristal conferem sofisticação incomum para a categoria. Sem bateria.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '43mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. J810',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável (jubilê)',
      funcoes: 'Hora, data, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '20',
    slug: 'citizen-bu0088-51h',
    brand: 'Citizen',
    model: 'Eco-Drive Multi-Function',
    reference: 'BU0088-51H',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-bu0088-51h.jpg'],
    description:
      'Relógio multifunção de alto impacto com mostrador esqueletizado azul/cinza e aro azul. Múltiplos subdials e calendário perpétuo posicionam este modelo no segmento de complicações acessíveis.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '44mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. H800',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Dia, data, mês, calendário anual, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '21',
    slug: 'citizen-ecodrive-bm7551-50x',
    brand: 'Citizen',
    model: 'Eco-Drive Bússola',
    reference: 'BM7551-50X',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-bm7551-50x.jpg'],
    description:
      'Eco-Drive com bezel bússola graduado e mostrador preto. Indicações de Norte/Sul/Leste/Oeste no aro externo. Para quem precisa de funcionalidade real no pulso, sem abrir mão do acabamento.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '43mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. E111',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Hora, data, bezel bússola, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '22',
    slug: 'citizen-ecodrive-bu2021-51l',
    brand: 'Citizen',
    model: 'Eco-Drive World Time',
    reference: 'BU2021-51L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-bu2021-51l.jpg'],
    description:
      'World time com mostrador azul e detalhes em dourado rosé. Exibe até 26 fusos horários simultaneamente. Uma das complicações mais úteis para quem viaja — tudo legível em um único olhar.',
    specs: {
      caixa: 'Aço inoxidável com detalhes rosé',
      diametro: '43mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. H804',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'World time (26 fusos), calendário, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '23',
    slug: 'citizen-ecodrive-ca4680-55l',
    brand: 'Citizen',
    model: 'Eco-Drive Chrono Rosé',
    reference: 'CA4680-55L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ca4680-55l.jpg'],
    description:
      'Cronógrafo Eco-Drive com mostrador azul-gelado e caixa em aço/rosé. Combinação de cores delicada com acabamento refinado — opção elegante para quem busca um cronógrafo sem peso esportivo.',
    specs: {
      caixa: 'Aço inoxidável com aro rosé',
      diametro: '39mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. B620',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Cronógrafo, data, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '24',
    slug: 'citizen-ecodrive-ca0610-52l',
    brand: 'Citizen',
    model: 'Eco-Drive Chronograph Azul',
    reference: 'CA0610-52L',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ca0610-52l.jpg'],
    description:
      'Cronógrafo Eco-Drive clássico com mostrador azul e caixa em aço polido. Três subdials limpos e leitura direta. Versão clean do cronógrafo solar — sem excessos, sem comprometer a função.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '44mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. H802',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Cronógrafo, data, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '25',
    slug: 'citizen-ecodrive-ca4507-84e',
    brand: 'Citizen',
    model: 'Eco-Drive Pulsômetro',
    reference: 'CA4507-84E',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/citizen-ca4507-84e.jpg'],
    description:
      'Cronógrafo Eco-Drive com escala pulsômetro no aro e mostrador creme sobre caixa gunmetal. Referência médica e estética vintage em um relógio solar moderno. Para quem aprecia raridade de uso.',
    specs: {
      caixa: 'Aço inoxidável PVD escuro',
      diametro: '44mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. B620',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável PVD escuro',
      funcoes: 'Cronógrafo, escala pulsômetro, data, Eco-Drive',
    },
    featured: false,
  },

  // ─── ORIENT ──────────────────────────────────────────────────────────────────

  {
    id: '26',
    slug: 'orient-classico-calendario-lua',
    brand: 'Orient',
    model: 'Clássico Calendário Multi-Mostrador',
    reference: 'RA-AK0507S10B',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/orient-classico-calendario-lua.png'],
    description:
      'Automático mecânico com mostrador champanhe e numerais romanos. Calendário multi-ano com sub-mostradores e fase da lua tornam este Orient Clássico uma das maiores relações custo-benefício em dress watches automáticos.',
    specs: {
      caixa: 'Aço inoxidável acabamento polido',
      diametro: '42mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático mecânico',
      calibre: 'Orient Cal. F6724',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Couro legítimo marrom escuro',
      funcoes: 'Calendário multi-ano, sub-mostradores, fase da lua',
    },
    featured: false,
  },
  {
    id: '27',
    slug: 'orient-bambino-automatico',
    brand: 'Orient',
    model: 'Bambino Sun & Moon',
    reference: 'RA-AK0011D10B',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    prontaEntrega: true,
    images: [
      '/products/orient-bambino-automatico.png',
      '/products/orient-bambino-automatico-2.png',
      '/products/orient-bambino-automatico-3.png',
    ],
    description:
      'Dress watch automático da linha Bambino com mostrador azul escuro e caixa dourada. Pulseira em couro azul marinho, com o charmoso indicador sol e lua (dia/noite) e dia da semana. Uma das poucas complicações românticas disponíveis nessa faixa de preço.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '41,5mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Orient Cal. F6924',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '30m / 3 bar',
      pulseira: 'Couro legítimo azul marinho',
      funcoes: 'Dia da semana, data, indicador sol e lua',
    },
    featured: false,
  },
  {
    id: '28',
    slug: 'orient-sport-ray-ii-all-black',
    brand: 'Orient',
    model: 'Sport Ray II All Black PVD',
    reference: 'RE-AC0Q02B00B',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/orient-sport-ray-ii-all-black.png'],
    description:
      'Diver automático da linha Sport Ray II em revestimento PVD total preto. Resistência a 200m, calibre F6922 e reserva de 40 horas. Presença imponente no pulso com acabamento stealth impecável.',
    specs: {
      caixa: 'Aço inoxidável PVD preto',
      diametro: '41,5mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Orient Cal. F6922',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '200m / 20 bar',
      pulseira: 'Aço inoxidável PVD preto',
      funcoes: 'Dia, data',
    },
    featured: false,
  },

  // ─── TISSOT ───────────────────────────────────────────────────────────────────

  {
    id: '29',
    slug: 'tissot-prx-ice-blue',
    brand: 'Tissot',
    model: 'PRX Mostrador Ice Blue',
    reference: 'T137.410.11.351.00',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/tissot-prx-ice-blue.png'],
    description:
      'O PRX é o relógio mais icônico da Tissot nos últimos anos — design integrado anos 70 com mostrador azul gelo sunburst e acabamento escovado. Quartzo suíço, safira e 100m. Referência indiscutível em elegância acessível.',
    specs: {
      caixa: 'Aço inoxidável design integrado',
      diametro: '40mm',
      cristal: 'Safira',
      movimento: 'Quartzo suíço',
      calibre: 'Tissot Cal. ETA G10.212',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável integrado',
      funcoes: 'Hora, minuto, segundo, calendário',
    },
    featured: true,
  },

  // ─── SEIKO (novos) ────────────────────────────────────────────────────────────

  {
    id: '30',
    slug: 'seiko-5-sports-champanhe-nato',
    brand: 'Seiko',
    model: '5 Sports Field Champanhe NATO',
    reference: 'SRPG35K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    prontaEntrega: true,
    images: [
      '/products/seiko-5-sports-champanhe-nato.png',
      '/products/seiko-5-sports-champanhe-nato-2.png',
      '/products/seiko-5-sports-champanhe-nato-3.png',
    ],
    description:
      'Field watch automático com mostrador champanhe e pulseira NATO em nylon areia. Leitura limpa com numerais arábicos e calendário dia/data. Combinação clássica de campo que nunca sai de moda.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '39,4mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'NATO em nylon tom areia',
      funcoes: 'Dia, data',
    },
    featured: false,
  },
  {
    id: '31',
    slug: 'seiko-5-sports-azul-sunburst-diver',
    brand: 'Seiko',
    model: '5 Sports Diver Azul Sunburst',
    reference: 'SRPD71K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/seiko-5-sports-azul-sunburst-diver.png'],
    description:
      'Diver automático com mostrador azul sunburst e bezel rotativo unidirecional azul. Bracelete Oyster em aço inox. Visual totalmente coeso e uma das configurações mais procuradas da linha 5 Sports atual.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável padrão Oyster',
      funcoes: 'Dia, data, bezel rotativo unidirecional',
    },
    featured: false,
  },
  {
    id: '32',
    slug: 'seiko-5-sports-all-black-pvd',
    brand: 'Seiko',
    model: '5 Sports Diver All Black PVD',
    reference: 'SRPD73K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/seiko-5-sports-all-black-pvd.png'],
    description:
      'Edição all-black em revestimento PVD total: caixa, bracelete e bezel preto fosco. Mostrador preto com marcadores de hora em relevo. Presença discreta e intensa ao mesmo tempo — referência no estilo stealth.',
    specs: {
      caixa: 'Aço inoxidável PVD preto',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável PVD preto',
      funcoes: 'Dia, data, bezel rotativo unidirecional',
    },
    featured: false,
  },
  {
    id: '33',
    slug: 'seiko-5-sports-preto-oyster',
    brand: 'Seiko',
    model: '5 Sports Diver Preto Aço',
    reference: 'SRPC61K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/seiko-5-sports-preto-oyster.png'],
    description:
      'Diver clássico com mostrador preto e bracelete Oyster em aço polido/escovado. Bezel unidirecional preto. O ponto de entrada perfeito para quem quer um automático esportivo sem peso visual excessivo.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável padrão Oyster',
      funcoes: 'Dia, data, bezel rotativo unidirecional',
    },
    featured: false,
  },
  {
    id: '34',
    slug: 'seiko-5-sports-automatico-black',
    brand: 'Seiko',
    model: '5 Sports Automático Black',
    reference: 'SNKL55K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/seiko-5-sports-automatico-black.png'],
    description:
      'Seiko 5 automático clássico com mostrador preto fosco e marcadores aplicados. Calendário duplo (dia/data) e movimento automático de 21 jewels. A entrada mais acessível do portfólio para quem quer um automático Seiko no pulso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 7S26 (21 jewels)',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Dia, data',
    },
    featured: false,
  },
  {
    id: '35',
    slug: 'seiko-5-sports-turquesa-srpd45k1',
    brand: 'Seiko',
    model: '5 Sports Diver Turquesa',
    reference: 'SRPD45K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    images: ['/products/seiko-5-sports-turquesa-srpd45k1.png'],
    description:
      'Diver automático com mostrador turquesa vibrante e calendário integrado multilíngue. Bracelete Oyster e bezel unidirecional. Uma das colorações mais reconhecíveis da linha 5 Sports — impossível passar despercebido.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável padrão Oyster',
      funcoes: 'Dia, data, calendário rotativo, bezel unidirecional',
    },
    featured: false,
  },
  {
    id: '36',
    slug: 'seiko-chronograph-verde-ssb481p1',
    brand: 'Seiko',
    model: 'Chronograph Verde Aço',
    reference: 'SSB481P1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true, // vendido
    prontaEntrega: true,
    images: [
      '/products/seiko-chronograph-verde-ssb481p1.png',
      '/products/seiko-chronograph-verde-ssb481p1-2.png',
    ],
    description:
      'Cronógrafo a quartzo com mostrador verde e detalhes prateados sobre bracelete de aço com fecho déployant. Aro tachymeter externo. O verde elegante nessa configuração é uma das propostas mais sofisticadas entre cronógrafos acessíveis.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '41,5mm',
      cristal: 'Hardlex Crystal',
      movimento: 'Quartzo (cronógrafo)',
      calibre: 'Seiko Cal. 8T63',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável com fecho déployant',
      funcoes: 'Cronógrafo 60 min, 24h, segundos contínuos, tachymeter',
    },
    featured: false,
  },

  // ─── CITIZEN (novos) ──────────────────────────────────────────────────────────

  {
    id: '37',
    slug: 'citizen-tsuyosa-vermelho-nj0150-56n',
    brand: 'Citizen',
    model: 'Tsuyosa Vermelho Sunburst',
    reference: 'NJ0150-56N',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true,
    images: ['/products/citizen-tsuyosa-vermelho.png'],
    description:
      'Tsuyosa automático com mostrador vermelho sunburst e calendário integrado. Caixa e bracelete em aço inoxidável com acabamento polido. A combinação de vermelho com aço puro é uma das mais impactantes do catálogo.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Citizen Cal. 8210',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável com fecho dobrável',
      funcoes: 'Hora, minuto, segundo, data',
    },
    featured: false,
  },

  // ─── ESTOQUE PRONTA ENTREGA — FORTALEZA ────────────────────────────────────────

  {
    id: '38',
    slug: 'tissot-prx-powermatic-80-preto',
    brand: 'Tissot',
    model: 'PRX Powermatic 80',
    reference: 'T137.407.11.051.00',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/tissot-prx-powermatic-80-preto.png'],
    description:
      'Versão automática do PRX, com mostrador preto texturizado em waffle e calibre Powermatic 80 — 80 horas de reserva de marcha. Caixa em aço 316L com pulseira integrada, cristal de safira com antirreflexo e fundo transparente que expõe o movimento. O design integrado dos anos 70 com a robustez de um automático suíço de verdade.',
    specs: {
      caixa: 'Aço inoxidável 316L design integrado',
      diametro: '40mm',
      cristal: 'Safira com antirreflexo',
      movimento: 'Automático suíço Powermatic 80',
      calibre: 'ETA Powermatic 80',
      reservaDeMarcha: '80 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável integrado',
      funcoes: 'Hora, minuto, segundo, data, fundo transparente',
    },
    featured: false,
  },
  {
    id: '39',
    slug: 'bulova-surveyor-automatic-champagne',
    brand: 'Bulova',
    model: 'Surveyor Automatic',
    reference: '96B470',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/bulova-surveyor-automatic-champagne.png'],
    description:
      'Automático com mostrador champanhe sunburst e caixa em aço de 39mm — proporção clássica que valoriza pulsos finos sem perder presença. Data com lupa às 3h, cristal de safira e fundo transparente revelando o calibre Miyota. Um Bulova discreto, elegante e versátil para o dia a dia.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '39mm',
      cristal: 'Safira',
      movimento: 'Automático',
      calibre: 'Miyota 8215 (21 jewels)',
      resistenciaAgua: '30m (splash)',
      pulseira: 'Aço inoxidável',
      funcoes: 'Hora, minuto, segundo, data com lupa, fundo transparente',
    },
    featured: false,
  },
  {
    id: '40',
    slug: 'citizen-promaster-diver-ecodrive-azul',
    brand: 'Citizen',
    model: 'Promaster Diver Eco-Drive',
    reference: 'BN0151-09L',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/citizen-promaster-diver-ecodrive-azul.png'],
    description:
      'Diver com certificação ISO, mostrador azul e pulseira de poliuretano na mesma cor — visual esportivo e uso real em água sem complicação. Tecnologia Eco-Drive elimina troca de bateria: carrega com qualquer fonte de luz. Bezel unidirecional, data e resistência a 200m.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42mm',
      cristal: 'Vidro mineral',
      movimento: 'Eco-Drive Solar (quartzo)',
      calibre: 'Citizen Cal. E168',
      resistenciaAgua: '200m / 20 bar',
      pulseira: 'Poliuretano azul',
      funcoes: 'Hora, data, bezel unidirecional, Eco-Drive',
    },
    featured: false,
  },
  {
    id: '41',
    slug: 'orient-kamasu-diver-preto',
    brand: 'Orient',
    model: 'Kamasu Diver',
    reference: 'RA-AA0001B19A',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true, // vendido
    prontaEntrega: true,
    images: ['/products/orient-kamasu-diver-preto.png'],
    description:
      'Diver automático com mostrador preto, bezel unidirecional de 120 cliques e coroa rosqueada — referência de entrada no mundo dos divers automáticos sérios. Calibre F6922 com corda manual e hacking, cristal de safira e resistência a 200m. Lacrado na caixa original Orient.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '41,8mm',
      cristal: 'Safira',
      movimento: 'Automático (corda manual e hacking)',
      calibre: 'Orient Cal. F6922',
      reservaDeMarcha: '40 horas',
      resistenciaAgua: '200m / 20 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Dia, data, bezel unidirecional 120 cliques, coroa rosqueada',
    },
    featured: false,
  },
  {
    id: '42',
    slug: 'seiko-5-sports-azul-skx',
    brand: 'Seiko',
    model: '5 Sports Diver Azul',
    reference: 'SRPD51K1',
    condition: 'Novo (lacrado)',
    fullSet: true,
    price: null,
    hidden: true, // vendido
    prontaEntrega: true,
    images: ['/products/seiko-5-sports-azul-skx.png'],
    description:
      'Diver automático com mostrador azul e bezel giratório no estilo SKX que consagrou a linha 5 Sports. Calibre 4R36 com corda manual e hacking, day-date e resistência a 100m. Acompanha pulseira de aço original e está na caixa, podendo ser usado também com pulseira NATO ou de borracha.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '42,5mm',
      cristal: 'Hardlex',
      movimento: 'Automático (corda manual e hacking)',
      calibre: 'Seiko Cal. 4R36',
      reservaDeMarcha: '41 horas',
      resistenciaAgua: '100m / 10 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Dia, data, bezel rotativo unidirecional',
    },
    featured: false,
  },
  {
    id: '43',
    slug: 'seiko-5-automatic-azul-7s26',
    brand: 'Seiko',
    model: '5 Automatic Azul',
    reference: '7S26-02H0',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: [
      '/products/seiko-5-automatic-azul-7s26.png',
      '/products/seiko-5-automatic-azul-7s26-2.png',
      '/products/seiko-5-automatic-azul-7s26-3.png',
    ],
    description:
      'O clássico Seiko 5 em mostrador azul, calibre 7S26 de 21 jewels — sem corda manual ou hacking, no espírito original da linha. Day-date às 3h e fundo transparente exibindo o movimento. Pulseira e caixa em aço. A entrada mais tradicional para quem quer um automático Seiko no pulso.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '37mm',
      cristal: 'Hardlex',
      movimento: 'Automático',
      calibre: 'Seiko Cal. 7S26 (21 jewels)',
      resistenciaAgua: '50m / 5 bar',
      pulseira: 'Aço inoxidável',
      funcoes: 'Dia, data, fundo transparente',
    },
    featured: false,
  },
  {
    id: '44',
    slug: 'bulova-surveyor-feminino-diamantes',
    brand: 'Bulova',
    model: 'Surveyor Feminino',
    reference: '96P229',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/bulova-surveyor-feminino-diamantes.png'],
    description:
      'Versão feminina do Surveyor, caixa de 31mm em aço com mostrador azul claro e marcadores de diamante. Quartzo Miyota, vidro mineral e fecho deployant com botões — discreto, delicado e de uso diário. Um presente certeiro ou peça de entrada para quem está montando a primeira coleção.',
    specs: {
      caixa: 'Aço inoxidável',
      diametro: '31mm',
      cristal: 'Vidro mineral',
      movimento: 'Quartzo',
      calibre: 'Miyota 2035',
      resistenciaAgua: '30m (splash)',
      pulseira: 'Aço inoxidável com fecho deployant',
      funcoes: 'Hora, minuto, segundo, marcadores em diamante',
    },
    featured: false,
  },
  {
    id: '45',
    slug: 'venezianico-redentore-bellanotte',
    brand: 'Venezianico',
    model: 'Redentore Bellanotte',
    reference: '1221575',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/venezianico-redentore-bellanotte.png'],
    description:
      'A peça mais rara do estoque: automático italiano com mostrador artístico off-center, combinando aventurina, madrepérola e baixos-relevos em latão rodiado retratando o horizonte de Veneza sob um céu estrelado. Caixa de 40mm em aço 316L, cristal de safira com antirreflexo e pulseira de couro italiano. Peça de colecionador para quem quer sair do óbvio.',
    specs: {
      caixa: 'Aço inoxidável 316L',
      diametro: '40mm',
      espessura: '11,5mm',
      cristal: 'Safira com antirreflexo',
      movimento: 'Automático',
      calibre: 'Miyota NH05A',
      resistenciaAgua: '50m / 5 ATM',
      pulseira: 'Couro italiano',
      funcoes: 'Hora, minuto, segundo, mostrador artístico off-center',
    },
    featured: true,
  },
  {
    id: '46',
    slug: 'bulova-classic-automatic-preto-dourado',
    brand: 'Bulova',
    model: 'Classic Automatic',
    reference: '96A203',
    condition: 'Como novo',
    fullSet: false,
    price: null,
    prontaEntrega: true,
    images: ['/products/bulova-classic-automatic-preto-dourado.png'],
    description:
      'Dress watch automático com mostrador preto e aro interno dourado — contraste clássico que funciona tanto com terno quanto no dia a dia. Data às 3h e pulseira de couro preto. Um automático de entrada elegante, sem o peso visual de um esportivo.',
    specs: {
      caixa: 'Aço inoxidável com detalhes dourados',
      diametro: '40mm',
      cristal: 'Vidro mineral',
      movimento: 'Automático',
      calibre: 'Miyota 8215 (21 jewels)',
      resistenciaAgua: '30m (splash)',
      pulseira: 'Couro preto',
      funcoes: 'Hora, minuto, segundo, data',
    },
    featured: false,
  },
]

export const visibleProducts = products.filter((p) => !p.hidden)

export const visibleBrandNames = new Set(visibleProducts.map((p) => p.brand.toLowerCase()))

export const prontaEntregaProducts = visibleProducts.filter((p) => p.prontaEntrega)

export function getProductBySlug(slug: string): Product | undefined {
  return visibleProducts.find((p) => p.slug === slug)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return visibleProducts
    .filter((p) => p.brand === product.brand && p.id !== product.id)
    .slice(0, limit)
}

export function getFeaturedProducts(limit = 4): Product[] {
  return visibleProducts.filter((p) => p.featured).slice(0, limit)
}

export function formatPrice(price: number | null): string {
  if (price === null) return 'Sob consulta'
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}
